### ISSUE TITLE
It works!

### ISSUE THREAD

**Issue by MagicFrogSJTU** [rwpenney/cxx-rtimers#1]
The code works in a amazingly quick and simple way! Thanks for your smart work!!  
Why not define a marco to reduce the two lines into one, as
```
#define ONELINE(name) \
    static rtimers::cxx11::DefaultTimer timer(name); \
    auto scopedStartStop = timer.scopedStart();
```

Thanks again!

**Comment by rwpenney** [comment]
Thanks, @MagicFrogSJTU for the good idea. I'm also pleased to hear that you are finding this package useful.

I've now added a `RTIMERS_STATIC_SCOPED` macro, which should cover not only the `rtimers::cxx11` namespace but also the Boost & Posix versions of the timer classes.
